### ISSUE TITLE
Strategy to get through open PRs

### ISSUE THREAD

**Issue by boydjohnson** [TheAlgorithms/Rust#117]
I noticed there are a bunch of open PRs that haven't been reviewed. Any interest from @AnshulMalik in giving more people merge access? I have some time right now to review PRs, so I am volunteering to review some PRs.

**Comment by AnshulMalik** [comment]
Hi @boydjohnson, yeah, I have been busy, so don't find much time to review the PRs, thanks for stepping up, I'll be more than happy if you can help us :)
