### ISSUE TITLE
Rewrite `Heap.rs`

### ISSUE THREAD

**Issue by k12ish** [TheAlgorithms/Rust#188]
This trivial test fails:
```rust
#[test]
fn test_empty_heap() {
    let mut heap = MaxHeap::new::<i32>();
    assert_eq!(heap.next(), None)
}
```

    ---- data_structures::heap::tests::test_empty_heap stdout ----
    thread 'data_structures::heap::tests::test_empty_heap' panicked at 'attempt to subtract with
    overflow', src/data_structures/heap.rs:117:9

Other big issues:

- `Vec` contains a length meaning that `count` is unneeded
-  The trait bound `Default` can be entirely removed with zero-based indexing, saving memory and making the implementation more flexible

I am more than happy to enact these changes, if that is acceptable to you.

**Comment by siriak** [comment]
Hi, you can make a PR to fix that and I'll get it reviewed and merged. Thanks for sharing!

**Comment by plaxi0s** [comment]
Hi I made to [PR](https://github.com/TheAlgorithms/Rust/pull/215) to fix this. Let me know if any other changes are required. 
Thanks!

**Comment by siriak** [comment]
Cool, thanks! Feel free to make more PRs if you want to fix something else
