### ISSUE TITLE
LinkedList leaks Node memory when dropped

### ISSUE THREAD

**Issue by Kylebrown9** [TheAlgorithms/Rust#242]
The [linked_list](https://github.com/TheAlgorithms/Rust/blob/master/src/data_structures/linked_list.rs) module stores references to nodes using `NonNull`s that are never dropped at any point.
Unless there is something I missed, this code doesn't ever free the memory allocated to the nodes.

**Comment by siriak** [comment]
@imp2002 could you verify if this is the case, please?

**Comment by imp2002** [comment]
@Kylebrown9 
Hello, why `NonNull` never dropped? Impl LinkedList in [rust-lang doc](https://doc.rust-lang.org/nightly/src/alloc/collections/linked_list.rs.html#50) with `NonNULL` too. Can you explain where is wrong? Thanks.

**Comment by Kylebrown9** [comment]
The LinkedList in the docs you referenced provides a `Drop` implementation (line 993) that performs the required freeing. Dropping `NonNull` itself does not free the referenced memory.

**Comment by imp2002** [comment]
Impl with `Box::from_raw()`. After calling this function, the raw pointer is owned by the resulting Box. Specifically, the Box destructor will call the destructor of T and free the allocated memory. 
```
fn pop_back_node(&mut self) -> Option<Box<Node<T>>> {
        self.tail.map(|node| unsafe {
            let node = Box::from_raw(node.as_ptr());
            self.tail = node.prev;

            match self.tail {
                None => self.head = None,
                Some(tail) => (*tail.as_ptr()).next = None,
            }

            self.len -= 1;
            node
        })
    }
```

**Comment by Kylebrown9** [comment]
Something like that could work.

Until `Drop` is implemented for `LinkedList` such that all nodes are freed, `LinkedList` will leaks node memory when dropped.
The drop implementation could use `Box::from_raw(...)` as you say or [`ptr::drop_in_place(...)`](https://doc.rust-lang.org/std/ptr/fn.drop_in_place.html).

This is a big issue with the example and should be fixed ASAP to avoid misleading readers on the use of `NonNull`.
