### ISSUE TITLE
open to adding benchmarks?

### ISSUE THREAD

**Issue by skewballfox** [TheAlgorithms/Rust#276]
hey, I recently had an assignment where I had to benchmark two sorting algorithms(selection and quick) against each other in order to create a hybrid, and did this using the sorting algorithms from this repository. I wrote the benchmarks using criterion, and was wondering if you would be open to adding benchmarks to this repository, it should be fairly trivial to take the benchmarks I created and refactor them to do benchmark all the comparative based sorting algorithms against each other. 

you can find the [benchmarks here](https://github.com/skewballfox/sorting_comparison/blob/master/benches/sorting_bench.rs) and I'll be adding the markdown version of the actual report shortly

**Comment by siriak** [comment]
I'm not sure about that, the benchmarks are not algorithms themselves, but maybe we could augment automated tests with benchmarks? @imp2002 any thoughts?

**Comment by skewballfox** [comment]
my main thinking was having a way to test various algorithms against each
other over many different sizes of input(and many different types of
input). this is beneficial because just because an algorithm is
asymptotically optimal in the worst case, it doesn't make it the fastest
for a given input (in respect to size or properties like whether it's
already sorted).

I think this would also be beneficial because so long as you are using
idiomatic rust, because rust is pretty close to the metal, you  would get a
good approximation of relative performance. In practice higher level
languages often have optimized functions that run ridiculously fast
compared to the rest of the code, which makes algorithm analysis a bit
difficult.

**Comment by skewballfox** [comment]
btw, I'm about to have to dive in to benchmarking again for two more assignments, and wanted to check on this again. If you feel like it's outside of the scope of what this repo is for, I can go ahead and close this

**Comment by siriak** [comment]
Feel free to add benchmarks, I think they will be useful
