### ISSUE TITLE
Have similar signatures to methods

### ISSUE THREAD

**Issue by yashwanthreddyg** [TheAlgorithms/Rust#29]
I think having similar signatures among methods that have same functionality (sorting, searching) should be followed. It is inconsistent if one sort accepts mutable vectors, another, mutable slices.
Having instance methods for something as simple as sort/search which doesn't require storing of a state also should be decided.

**Comment by AnshulMalik** [comment]
Yep, we should totally decide that.

So what do you think, we should keep mutable vectors or mutable slices.

I have one more concern in mind, should we mutate the vector passed to us, or create another sorted vector and return.

**Comment by yashwanthreddyg** [comment]
Personally, I thing having mutable slices should be the way to go since Vector is a wrapper on top of that (atleast I guess). Also, I think our functions should mutate their parameters as it is a common practice among various languages. Please see my references
https://docs.oracle.com/javase/6/docs/api/java/util/Arrays.html#sort(int[])
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by efugier** [comment]
I do agree with this, mutable slices are the type to go with.

**Comment by AnshulMalik** [comment]
Cool, slices can work everywhere, so let's use them :)
