### ISSUE TITLE
Add more algorithms in Rust Language

### ISSUE THREAD

**Issue by r0hit-gupta** [TheAlgorithms/Rust#3]
This issue is fairly easy and most beginners should be comfortable implementing algorithms of their choice in Rust. In case of any problem, raise an issue or just discuss it below.

**Graphs**
 - [ ] DFS

**Dynamic Programming**
 - [ ] Longest increasing subsequence()
 - [ ] Rod cut
 - [ ] Egg Dropping Puzzle
 
**Data Structures**
 - [ ] Graph
   - [ ] Directed
   - [ ] Undirected
 - [ ] Trie
 - [ ] AVL Tree

**General**
 - [ ] N-Queens
 - [ ] Graph Coloring
 - [ ] Run Length Encoding

**Project Euler**, **LeetCode**, etc.
 - Currently, we don't accept problems from those and similar websites

**Comment by nlynchjo** [comment]
@r0hit-gupta I am also looking for a first time contribution! Mind if I take on some of the data structures?

**Comment by r0hit-gupta** [comment]
@0xazure @nlynchjo Please feel free to contribute and work on anything you like. Take an idea from other repositories if you do not know how to begin. Send a pull request and if there is something not right, we will let you know. Cheers!

**Comment by darkyshiny** [comment]
@r0hit-gupta I'll take a crack at the KMP string pattern matching 👍

**Comment by bofh69** [comment]
@0xazure - sorry, I didn't read your comment until now. I just added a PR with insertion sort.

**Comment by 0xazure** [comment]
@bofh69 thanks for letting me know! I hadn't actually started implementing it yet, so I'll focus on the selection sort. I'm definitely interested in how you did it in Rust, so I'll have a look at your PR!

**Comment by bofh69** [comment]
@0xazure Great! I felt a bit stupid not checking the comments here first...
My solution is probably not the best, I'm still learning Rust, but now it is decent.

**Comment by eisterman** [comment]
I'm actually working on Merge Sort

**Comment by AnshulMalik** [comment]
I think there is already a PR for Merge Sort @eisterman

**Comment by Jay9596** [comment]
I'd like to work on implementing Queue, if no one has claimed it.

**Comment by AnshulMalik** [comment]
Go ahead @Jay9596 :)

**Comment by ra-kete** [comment]
I'd like to try my hands on heap sort.

**Comment by DanielSauve** [comment]
I'll take a shot at making a Stack

**Comment by BaxterEaves** [comment]
I'm up for k-means, but i'm not aware of a dynamic programming algorithm for data with more than one dimension. I can implement the more general iterative algorithm if you like.

**Comment by pickfire** [comment]
I am interested in caesar cipher.

**Comment by AnshulMalik** [comment]
Give it a try @BaxterEaves and @pickfire 👍

**Comment by elpiel** [comment]
I've added Merge Sort, I will try to do some other as well PR #57

**Comment by pickfire** [comment]
@AnshulMalik I have added the caesar cipher https://github.com/TheAlgorithms/Rust/pull/55

**Comment by leviathan88** [comment]
@r0hit-gupta I add PR for Longest common subsequence, still not merged ?

**Comment by sstadick** [comment]
I will take a crack at a few of these!
It looks like there's a Radix Sort PR in progress, what's the status there?

**Comment by kitlith** [comment]
I noticed Linked Lists are listed, I think this does the subject the most justice: https://rust-unofficial.github.io/too-many-lists/

**Comment by fabrizzioalco** [comment]
Hey I'll try to do Dijkstra algorithm

**Comment by cfvescovo** [comment]
I'd like to work on some ciphers (e.g. four-square and playfair)

**Comment by douglasOlv** [comment]
would like to work on coin change, what's the status?

**Comment by pgimalac** [comment]
I'm not sure sharing solutions of the Project Euler is a very good idea, I think it goes against the objective of the challenges...

**Comment by NickTheBit** [comment]
I would like to make an attempt on towers of hanoy, if it's possible

**Comment by joao-conde** [comment]
@r0hit-gupta Im thinking on contributing. I notice there are not enough tests. Can I implement the following:

1. `dynamic_programming/01_knapsack.rs`
2. `dynamic_programming/coin_change.rs`
3. a final PR with unit tests for the above and tests for all the sort algorithms?

**Comment by marnagy** [comment]
@r0hit-gupta Hello, I am a bit new to Rust, but can I make implementations of:
- Trie
- Graph
?

**Comment by ulwlu** [comment]
I wonder if there are enough reviewers in this repository.
Some PR is not reviewed for months, and it reduce the committer's motivation.

**Comment by pickfire** [comment]
@ayaankhan98 If no one is currently maintaining it, I can help to temporary maintain the repo to reduce the amount of open pull requests and help to review them at the same time if I have time.

**Comment by ayaankhan98** [comment]
> @ayaankhan98 If no one is currently maintaining it, I can help to temporary maintain the repo to reduce the amount of open pull requests and help to review them at the same time if I have time.

Yes, sure @pickfire go ahead. Thanks for your support.

**Comment by cfvescovo** [comment]
If you need any help, count me in too.
I would be glad to help you maintain the repo.

**Comment by marnagy** [comment]
Is there any algorithm I can help with? Contact me if I can help with anything.

**Comment by jonakrumrein** [comment]
I would like to implement the following algorithms with a fellow student as a project for our Rust lecture at the Corporate University DHBW Stuttgart.

- Transposition Cipher
- n-queens Problem
- Rod cut

**Comment by alexfertel** [comment]
Hello! I see this repo is unmaintained, but I think it provides a lot of value for the community, so I decide to make my own, which you can find in https://github.com/alexfertel/rust-algorithms.

Right now it is missing some README files, but I'll be adding those soon! I started by adding the sorting algorithms but feel free to contribute with your own. 🚀

**Comment by siriak** [comment]
Hi @alexfertel, I'm cleaning up this repo at the moment and will continually review new submissions, so feel free to contribute here too :)

**Comment by shadiakiki1986** [comment]
n-queens: https://github.com/insou22/typing-the-technical-interview-rust/

**Comment by MatheusMuriel** [comment]
Hello, i will work on DFS Graph Algorithm

**Comment by elpiel** [comment]
Dijstra is actually implemented but not marked as one @r0hit-gupta

**Comment by er888kh** [comment]
I think we can implement some items on this list:
## Math
- [ ] Random number generation
- [ ] Integer factorization (for up to 128 bit integers)
- [ ] Integration
## Graph and Trees
- [ ] Lowest common ancestor
- [ ] Prufer encoding (WIP by me)
- [ ] Strongly Connected Component tasks
- [ ] Heavy Light Decomposition
- [ ] Centroid, centroid decomposition
- [ ] Max flow, min cost max flow
- [ ] All pairs shortest path
## Searching
- [ ] Ternary search
## Strings
- [ ] Suffix array, suffix tree

I'm sure I'm missing many algorithms.

**Comment by mime8** [comment]
Hi, all! I'd like to work on ternary search algorithm, if no one else is working on it.

**Comment by er888kh** [comment]
> Hi, all! I'd like to work on ternary search algorithm, if no one else is working on it.

Awesome! I add your name to the list.

**Comment by b42thomas** [comment]
Hey y'all, I'm looking to make my first contribution.  I would like to work on the matrix operations.  Should that be separated into different PRs for addition, subtraction and multiplication?

**Comment by siriak** [comment]
@b42thomas depending on how complex they are. If you're implementing naive approaches, they can be merged together, if some complex algorithms, better to do them separately

**Comment by er888kh** [comment]
@siriak I have a question:
I want to implement a few graph algorithms, and if they are represented using `BTreeMap`, a `log(n)` factor would be added to their time complexity (obviously.) So can I only implement the algorithms for graphs with vertices numbered from 1 to n and having `&[Vec<usize>]` as their adjacency list?

I know we are supposed to create generic algorithms, but adding a `log(n)` to max flow wouldn't make anyone happy.

**Comment by siriak** [comment]
@er888kh, I think we can have both versions. Depending on the task at hand, both can be useful.

**Comment by er888kh** [comment]
> @er888kh, I think we can have both versions. Depending on the task at hand, both can be useful.

That's certainly an option, but it would create a lot of duplication (or at least generics boiler plate)

Another solution is to have a seperate implementation that enumerates graphs represented using BTreeMap to a convenient representation. Then anyone can use that instead. As an added bonus, this solution wouldn't change the time complexity, as iterating over a BTree can be done in O(n).

I will implement the option you choose (my code wouldn't be ready for at least a few days though, I'm too busy)

**Comment by siriak** [comment]
Agree, let's implement for the `from 1 to n` case then

**Comment by mime8** [comment]
While, my PR for ternary search is still in review, I'd like to work on Ternary Search Tree. I don't see this data structure in the project.

**Comment by mhorst00** [comment]
@leonamtmann and me want to implement a couple of algorithms requested here. Right now we are working on these 3:

- Gauss-Elimination
- Newton-Raphson method derivation
- Basic matrix operations: add, subtract, multiply

All of these should be generic.

**Comment by er888kh** [comment]
Now that I have added (#309), it should be really easy to implement 2-SAT problem's solution.
Here is my CPP [implementation](https://gist.github.com/er888kh/4201fc1c80a2d7f66de3422e1d314504) if anyone is interested.

**Comment by er888kh** [comment]
@siriak, what is your opinion about moving towards creating a general purpose crate for crates.io? We already have the "basic infrastructure" and people can really benefit from these implementations.

**Comment by siriak** [comment]
In general, I like the idea, but let's discuss it in more detail on our Discord server https://discord.gg/adJacSyV

**Comment by er888kh** [comment]
I have an idea for implementing big number support:

First, One can implement a really basic base 10 big number module. It only supports addition and multiplication by 2. It can be formatted as a string and can be created from a string.

After that, a big number module can be implemented that is basically just a BitSet with usual operations (addition, multiplication, division, ...). Converting to and from strings can then be handled using the base 10 implementation.

Right now I am just way too busy, and I will not have time to implement these, plus the second one will have a ton of boring boilerplate. Can someone implement (or even just partially implement) any of the above modules?

Also, there might be simpler approaches to this problem, so other suggestions are welcome.

**Comment by kou-sia** [comment]
I want to run＿length＿encoding.
This is because 'burrows_wheeler_transform' is already implemented and it would be beneficial to add 'run_length_encoding' to the library, which is often performed following this algorithm.

**Comment by aryan20sri** [comment]
Hey, can I work on run length encoding? I'm familiar with the algorithm and feel it would be fairly straightforward to implement an encoder and decoder both.

**Comment by kou-sia** [comment]
I've implemented it before. 
So if you want to add run length, I suggest you revamp the existing source code.
What do you think?

https://github.com/TheAlgorithms/Rust/commits/master/src/string/run_length_encoding.rs
