### ISSUE TITLE
Bug in `string/aho_corasick` algorithm

### ISSUE THREAD

**Issue by guopenghui** [TheAlgorithms/Rust#319]
https://github.com/TheAlgorithms/Rust/blob/a5cf37c397d097305f52736d6305d22f22b7b82a/src/string/aho_corasick.rs#L80

It will cause computing overflow when pattern appear at head of string.

If `i - len + 1 == 0`,  `i - len` will be `-1` first,  then panic.

Change to `i + 1 - len` will solve this.

**Comment by siriak** [comment]
Thanks for reporting, could you make a PR with the proposed changes?
