### ISSUE TITLE
Move tests to individual modules from lib.rs

### ISSUE THREAD

**Issue by AnshulMalik** [TheAlgorithms/Rust#33]
It's better if we write tests where we define the function, so it's easier to find.

There are few tests for search algorithms in https://github.com/TheAlgorithms/Rust/blob/master/src/lib.rs

We should move them to their modules

**Comment by efugier** [comment]
on it !

**Comment by efugier** [comment]
* Done for `/searching/` #34 
* Updated #24 accordingly

**Comment by efugier** [comment]
As a more global issue, i think a `CONTRIBUTING.md` should be written asap.

I don't really have the time to do it know, but `/searching` could serve as a template.

**Comment by AnshulMalik** [comment]
Yep, let's create another issue for `CONTRIBUTING.md`
