### ISSUE TITLE
Consider contributing this code to Rosetta Code?

### ISSUE THREAD

**Issue by tif-calin** [TheAlgorithms/Rust#372]
[Rosetta Code](https://rosettacode.org/wiki/FizzBuzz) is a wiki of common programming problems, algorithms, etc written in different programming languages.

Another, smaller, but similar site is [Programming Idioms](https://programming-idioms.org/all-idioms)

Rosetta Code is by far the most complete such project however. The entry for FizzBuzz for example contains solutions in 347 different languages

**Comment by siriak** [comment]
You can contribute it, it's MIT-licensed, after all
