### ISSUE TITLE
Multiple Clippy `#[allow(...)]` in codebase

### ISSUE THREAD

**Issue by Arjun31415** [TheAlgorithms/Rust#397]
There are multiple `allow` statements in the codebase -
1. Few in heap 
     https://github.com/TheAlgorithms/Rust/blob/fbc20a77e9f86313679e2c81f4f3bdaf4b0d63aa/src/data_structures/heap.rs#L136-L138
     https://github.com/TheAlgorithms/Rust/blob/fbc20a77e9f86313679e2c81f4f3bdaf4b0d63aa/src/data_structures/heap.rs#L148-L150
2. In SHA256- https://github.com/TheAlgorithms/Rust/blob/fbc20a77e9f86313679e2c81f4f3bdaf4b0d63aa/src/ciphers/sha256.rs#L103-L106
3. In Salsa Cipher -
    https://github.com/TheAlgorithms/Rust/blob/fbc20a77e9f86313679e2c81f4f3bdaf4b0d63aa/src/ciphers/salsa.rs#L17-L19
4. In N-Queens-
    https://github.com/TheAlgorithms/Rust/blob/fbc20a77e9f86313679e2c81f4f3bdaf4b0d63aa/src/general/nqueens.rs#L1-L5

These are only few of them. 
Should these be resolved or ignored ?

**Comment by siriak** [comment]
Done
