### ISSUE TITLE
Constraint Satisfaction Problem

### ISSUE THREAD

**Issue by MVanderloo** [TheAlgorithms/Rust#430]
There are multiple problems in the repo that fall under CSP. Essentially a list of variables and constraints between them. It is not an algorithm but a class of problems that can be modeled in such a way, such as sudoku, n queens, graph coloring. There are multiple ways to solve them, one being backtracking. Could be considered a data structure? Otherwise I don’t know where it would live. I recently did an assignment for school in golang to make a sudoku and killer sudoku solver where we convert to a generic CSP to solve. 

Where could this live in the repo? It’s difficult to define every constraint that a problem would use but you can cover most problems with EQUALS and NOT_EQUALS constraints. Or maybe there is a good way to define constraints by passing in some lambda functions. I’m not super experienced in rust but this could be something I’d be interested to contribute.

**Comment by siriak** [comment]
I'm not entirely sure that I get it. So you want to make sure all the e.g. sudoku solvers accept input in the same format? That's a good idea, I think you might use traits for that.

**Comment by skewballfox** [comment]
> I'm not entirely sure that I get it. So you want to make sure all the e.g. sudoku solvers accept input in the same format? That's a good idea, I think you might use traits for that.

Please correct me if I'm wrong, but I think he means a more generalized [linear solver](https://en.wikipedia.org/wiki/Linear_programming), you describe the problem as a set of variables and constraints, and the algorithm finds an optimal solution which satisfies those constraints, if it exist.

**Comment by siriak** [comment]
@MVanderloo, I think you could add it to Math section if it's generalized and make an adapter to transform a Sudoku problem to a generic problem statement

**Comment by appgurueu** [comment]
> Please correct me if I'm wrong, but I think he means a more generalized [linear solver](https://en.wikipedia.org/wiki/Linear_programming), you describe the problem as a set of variables and constraints, and the algorithm finds an optimal solution which satisfies those constraints, if it exist.

I don't think it's necessary about a linear solver but rather about solving boolean satisfiability problems (e.g. Sudoku can be modeled as a SAT problem).

**Comment by MVanderloo** [comment]
So my experience with this problem is creating a Constraint Satisfaction Problem solver, but yes I believe it can be generalized to Integer Linear Programming.  I might need to do a bit more research on the problem definitions but the algorithms I am familiar with solve for finite domains (integers) rather than a domain of say, any number between 0 and 1.
