### ISSUE TITLE
Remove the algorithm list from the `README.md` file

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/Rust#452]
### Description

We should remove the whole algorithm list from the `README.md` file.
Here are a few reasons why we should do this:

1. The links may be outdated in the future if the folder names are changed or such.
2. There's already a provided `DIRECTORY.md` file with a list of all algorithms.
3. It makes the `README.md` file longer and a bit more unreadable, IMO.

What do you think about this? Thanks. 🙂

**Comment by imp2002** [comment]
Agree.
