### ISSUE TITLE
Is the Travis workflow still being used?

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/Rust#453]
### Description

There seems to be a `.travis.yml` file, but I do not see any Travis runs on each commit.
Is it still being used? If so, we might want to move to GitHub Actions, which is faster and much easier.

If you agree with using GitHub Actions, I'd like to work on this. 🙂

**Comment by imp2002** [comment]
We are already using Github actions.

![image](https://user-images.githubusercontent.com/41513919/218045655-8d992c77-637e-4934-a5c2-6aeae0d2b405.png)
