### ISSUE TITLE
Port build_directory_md from Python to Rust

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Rust#473]
The [`build_directory_md.py`](../blob/master/.github/workflows/scripts/build_directory_md.py) run in our GitHub Action [directory_workflow.yml](../blob/master/.github/workflows/directory_workflow.yml#L18) should be replaced by Rust code.

This process should be done in ___three separate pull requests___.
* [x] Run both the Python and Rust versions in the same GitHub Action and fail if the two files are not identical.
* [x] Remove the running of the Python code in the GitHub Action and remove the Python file.
* [ ] [_Optional_] Modify the Rust version to add any new information and/or look and feel.

**Comment by siriak** [comment]
Why should we replace the existing script?

**Comment by cclauss** [comment]
Because:
1. It might be a change of pace for a contributor to contribute something that is not an algorithm.
2. Learning how GitHub Actions work and how to improve them is a superpower.
3. This community will be better able to maintain and improve code written in Rust.
4. I may port innovations made in the new implementation back into the Python repo.

**Comment by siriak** [comment]
Agree, let's do it then

**Comment by siriak** [comment]
Let's keep this open for a while in case somebody wants to update the Rust script with new features. I can't think of any off the top of my head, but this doesn't mean there are none
