### ISSUE TITLE
...and how do you use them?

### ISSUE THREAD

**Issue by GrosserKaese** [TheAlgorithms/Rust#517]
Hi guys,
thanks for this amazing project, really appreciate it! But here is one thing, and I feel like the most major idiot here, but I have to ask:

How do you use all these algorithms?

I mean, I did figure out you can not compile them one by one and have to 'cargo build' them, but then what? I am not experienced enough what to do next, and since the targets that got built aren't really readable or useful, how to use these algorithms?

Thanks!

**Comment by siriak** [comment]
This is a library that can be used in other applications. You need to write application code that has an entry point, accepts user input, and transforms it into inputs to one of the implemented algorithms. Then the algorithm processes it, and you can present results in the format you like.

**Comment by GrosserKaese** [comment]
Thanks! Question fully answered.
