### ISSUE TITLE
github actions is in outdated version

### ISSUE THREAD

**Issue by Raghav-Bell** [TheAlgorithms/Rust#543]
`actions/checkout` now in version 4 uses `node 20` :
https://github.com/TheAlgorithms/Rust/blob/b4cf132df2e6730ab64c6b096624571c623cadec/.github/workflows/directory_workflow.yml#L9
`git diff` can be replaced in newer versions as ( [How to run git diff in github actions](https://stackoverflow.com/questions/65944700/how-to-run-git-diff-in-github-actions)) :
```
- uses: actions/checkout@v3
  with:
    fetch-depth: 0
```

**Comment by siriak** [comment]
Are you willing to update it or somebody else can pick this up?

**Comment by Raghav-Bell** [comment]
@siriak , Yes please assign this issue to me.
