### ISSUE TITLE
How to implement Vigenere cipher?

### ISSUE THREAD

**Issue by onsah** [TheAlgorithms/Rust#56]
I have a complete Vigenere encrypt algorithm written in Rust. However, my algorithm assumes that all characters in the text is ASCII. Since Rust strings are unicode encoded I think this is an implementation problem. The another problem is to make it work for other languages than English. I thought algorithm can take a trait (maybe called as `Language`?) along with the text and key. In that way users can add their traits for their own languages.

**Comment by AnshulMalik** [comment]
This is a really interesting question @Furyzer0 
We have a PR that ignores non-ascii characters, the traditional way of doing.
I'll do some more research on this and get back here.

**Comment by AnshulMalik** [comment]
I have a simple idea to tackle this:
The characters from some language are in a specific range in unicode, so given a character, we can know what language it belongs to.
Now that we have the language, we already know it's range, so we can get the charset from that language and use that to compute anything.

Please let me know what you think about this.

**Comment by b4skyx** [comment]
Can we not use an external crate to handle graphemes, or use unstable rust to tackle the problem.
Check [https://doc.rust-lang.org/1.3.0/std/str/struct.Graphemes.html](Graphemes).
[https://crates.io/crates/unicode-segmentation](Unicode Segmentation)

**Comment by b4skyx** [comment]
An external crate such as [unicode-Segmentation](https://crates.io/crates/unicode-segmentation) can be used to handle graphemens in a language. Or use [unstable rust](https://doc.rust-lang.org/1.3.0/std/str/struct.Graphemes.html) to counter this problem as it has graphemes in std library to iterate over them.

**Comment by marnagy** [comment]
How about using the text as array of bytes and endoce those instead?
Than unicode shouldn't be a problem.

**Comment by marnagy** [comment]
*encode
