### ISSUE TITLE
DIRECTORY.md is out of date

### ISSUE THREAD

**Issue by CSRessel** [TheAlgorithms/Rust#591]
Algorithms and their links are missing from the `DIRECTORY.md` file. I can add these in a PR after comparing the contents of each directory, and I'd also like to update the PR checklist to include this update step so that it's less likely to be forgotten in the future.

**Comment by siriak** [comment]
There is a workflow that should be updating DIRECTORY, but it fails with access issues, could you look into that? Updating it manually is not sustainable. Let's keep this issue open so that maybe it's fixed at some point :)

**Comment by CSRessel** [comment]
Great suggestion, I was thinking it would be nice to automate but I see what you mean; there's already a script in the workflows for that. I'll take a look into that!

**Comment by CSRessel** [comment]
@siriak I think that between when the directory workflow was created and now, additional branch protections have likely been added. However, since I can't see the repo settings/branch protections, a little help would be needed! I have a proposed solution here: https://github.com/TheAlgorithms/Rust/pull/596

If you take a look, can you let me know if that looks feasible with what you're seeing in the branch protections? Or if I'm referencing options that aren't appearing there. And I'll leave that PR as WIP until you confirm that it seems like a working solution for the workflow permissions

Thanks for your help!

**Comment by siriak** [comment]
Sorry, I didn't have time to check today. I'll do it tomorrow or in a few days.

**Comment by siriak** [comment]
Let's keep the discussion in #596

**Comment by CSRessel** [comment]
I think this is probably good to close! Given that the associated PR merge automatically updated the directory as anticipated: https://github.com/TheAlgorithms/Rust/commit/d1ffaa27717c56408188677a857bb7ff1b0ba84f

**Comment by siriak** [comment]
Thanks, @CSRessel!
