### ISSUE TITLE
Many implementations are not declared as mods anywhere in the module tree

### ISSUE THREAD

**Issue by CSRessel** [TheAlgorithms/Rust#593]
Many implementations were never added to the `mod.rs` file in their directory. As a result, some of these files are unformatted or unlinted, and in the case of wiggle sort, the testing is incorrect.

In addition to adding the missing mod declarations for each algorithm that was missed, it would be good to include a checklist item in the PR template for adding the new code to the mod declarations.

I can take up this work in a PR that I've been working on locally.

**Comment by siriak** [comment]
Done, thanks!
