### ISSUE TITLE
Add algorithm to find k-th digit in a digit string

### ISSUE THREAD

**Issue by iagorrr** [TheAlgorithms/Rust#626]
A digit string is formed by concatenating consecutive numbers in a sequence. For instance, a digit string starting at 1 and ending at 10 would appear as follows: 1 2 3 4 5 6 7 8 9 10 -> "12345678910". There is some interesting queries like finding the digit at position k, where k can be as large as $10^{18}$ or even $10^9$, which requires an efficient algorithm without explicitly constructing the entire string.

I'm eager to develop and submit this algorithm in the coming days.

**Comment by siriak** [comment]
Hi, is this a well-known problem or a coding challenge? We do not add problems from leetcode and similar places. Please add a Wikipedia link or a link to an online book or some other reputable information source where I can read more about the problem.
