### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by AnshulMalik** [TheAlgorithms/Rust#8]
We should have a readme with some info just like other repositories have [Python](https://github.com/TheAlgorithms/Python). 

It should just highlight the things that we have implemented and the things which are yet to be implemented.

For now, it should just contain the headlines for different categories of algorithms and later, we can fill them with specific algorithms.

**Comment by camilosampedro** [comment]
I want to work on this issue. Can I help you?

**Comment by AnshulMalik** [comment]
Yes, sure @camilosampedro. Thanks :)
